### ISSUE TITLE
Expose show_outer_percentiles arg

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-actions/deciles-charts#21]
The default behaviour is for the outer percentiles (1-9, 91-99) to be plotted. 

Often, this detail isn't needed and makes the charts noisy, so we just plot the deciles E.g [SRO-report](https://reports.opensafely.org/reports/sro-measures/)

It would be useful to expose the `show_outer_percentiles` argument [here](https://github.com/ebmdatalab/datalab-pandas/blob/master/ebmdatalab/charts.py#L47) when specifying the action.

**Comment by iaindillingham** [comment]
Do I need to be logged into the reports site to follow those links, @LFISHER7? (They're 404ing for me.)

I've made a comment on the associated PR that I could equally have made here. Essentially, it's preferable to pass options through the `config` key, rather than through arguments. Could you consider what we'd like the `config` key to look like?

**Comment by LFISHER7** [comment]
Ah you do, there's an example figure below from the first link, and the second link was wrong! (now updated)

![Screenshot 2022-04-19 at 17 59 42](https://user-images.githubusercontent.com/37254732/164058008-b9413f2d-f42f-40a7-97a7-5f28fb4275c7.png)

Sorry to have forgotten about the existence of `config` and glossed over #4 . I'll have a think of how we can incorporate this with the existing suggestions
